name : "Terraform Apply Infrastructure"

on:
   # For Manual Trigger
  workflow_dispatch:  
  
jobs:
        
  initialization: 
     runs-on : ubuntu-latest
     steps:
     - uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id : '${{ secrets.AWS_ACCESS_KEY }}'
          aws-secret-access-key : '${{ secrets.AWS_SECRET_KEY }}'
          aws-region: us-east-1

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2

     - name : Terraform Init
       run : terraform init

     - name : Terraform Plan
       run : terraform plan
         
         
  create-resources: 
     needs : initialization
     runs-on : ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id : '${{ secrets.AWS_ACCESS_KEY }}'
          aws-secret-access-key : '${{ secrets.AWS_SECRET_KEY }}'
          aws-region: us-east-1

      - name : Terraform Init
        run : terraform init

      - name : Terraform Apply
        run : terraform apply -auto-approve
